// Generated by CoffeeScript 2.5.1
export default {
  "resolution": {
    "width": 1920,
    "height": 1080
  },
  "mainPalette": {
    "color0": "#222831", // background color
    "color1": "#e8e8e8",
    "color2": "#f05454",
    "color3": "#30475e"
  },
  "shapes": {
    "amount": "3",
    "type": "circles"
  }
};

//TODO: write it as an object with getters and setters?
